#!/usr/bin/env ruby

require 'date'

current_dir = ARGV[0] || '.'
git_author = `git config --get github.user`.chomp

today = Date.today
offset = today.monday? ? 3 : 1
work_day = (Date.today - offset).strftime '%F'

subdirs = Dir.glob(File.join(current_dir, '**')).select {|f| File.directory? f}

def git_repo? full_path
  File.directory?(File.join(full_path, '.git'))
end

git_repos = subdirs.inject([]) do |git_dirs, dir_path|
  git_dirs << dir_path if git_repo?(dir_path) 
  git_dirs
end

commits = Hash.new {|h,k| h[k] = []}

git_repos.each do |repo|
  Dir.chdir repo do
    logs = `git log --date=short --format='%an|%cn|%ad|%s' --author=#{git_author}`
    logs.each_line do |line|
      date, message = line.match(/(\d{4}-\d{2}-\d{2})\|(.+)/).captures
      commits[File.basename repo] << message if date == work_day
    end
  end  
end

commits.each do |repo_name, messages|
  puts "[#{repo_name}]"
  messages.each do |message|
    puts "\t#{message}" 
  end
end
